# Generated by Django 5.1.1 on 2024-10-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseAPI", "0002_order_orderitem_review_shippingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
